POST http://localhost:3003/api/blogs
Content-Type: application/json

{
"title": "String2",
  "author": "String2",
  "url": "String2",
  "likes": 4
}

DELETE http://localhost:3003/api/blogs/610d2da5a5a2fc633dae0a14
Content-Type: application/json